# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# Allow nobody user to use passwordless sudo
.echo_template: &echo_template |
  echo 'nobody ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers

default:
  image: archlinux:latest

stages:          # List of stages for jobs, and their order of execution
  - build
  - release

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  before_script:
    - pacman -Syu --noconfirm
    - pacman -S git base-devel wget --noconfirm --needed
    - *echo_template
    - wget https://gitlab.com/binarycraft/packages/-/jobs/2963386497/artifacts/raw/zig-dev-bin-20220901-1-x86_64.pkg.tar.zst -O /tmp/zig.pkg.tar.zst
    - pacman -U /tmp/zig.pkg.tar.zst --noconfirm
    - rm /tmp/zig.pkg.tar.zst
    - echo $CI_JOB_ID
    # Writing GE_JOB_ID variable to environment file, will need the value in the next stage.
    - echo GE_JOB_ID=$CI_JOB_ID >> generate_executables.env
  script:
    - zig version
    - zig build -Drelease-fast=true
    - mkdir dist
    - cp src/builder.ui zig-out/bin/
    - tar -cvzf dist/gtk-examples-zig.tar.gz zig-out/bin/*
  artifacts:
    paths:
      - dist/gtk-examples-zig.tar.gz
    reports:
      # To ensure we've access to this file in the next stage
      dotenv: generate_executables.env
  timeout: 3 h
  only:
    # Can be removed if you want to trigger the pipeline for merge request or other branches
    - main

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo 'running release_job'
    - echo 'Previous Job ID is printed below'
    - echo $GE_JOB_ID
  # Specifying that this job requires artifacts from the previous job to succeed
  needs:
    - job: build-job
      artifacts: true
  release:
    name: 'Release Executables $CI_COMMIT_SHORT_SHA'
    description: 'Created using the release-cli'
    # tag_name is a mendatory field and can not be an empty string
    tag_name: '$CI_COMMIT_SHORT_SHA'
    assets:
      links:
        - name: 'gtk examples in zig for linux x86_64(binaries)'
          url: 'https://gitlab.com/binarycraft/gtk-examples-zig/-/jobs/${GE_JOB_ID}/artifacts/raw/dist/gtk-examples-zig.tar.gz'
  only:
    # Can be removed if you want to trigger the pipeline for merge request or other branches
    - main
